language: node_js
node_js:
  - "node"

script:
  - npm run lint
  - npm run test:ci
  - npm run build
  - if [ $TRAVIS_BRANCH == 'master' ]; then npm run release; fi

deploy:
  - provider: npm
    email: "techleadcommunity@norauto.com"
    api_key: $NPM_TOKEN
    on:
      branch: master